services:
  postgres:
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=simple_bank

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - DB_SOURCE=postgresql://root:1234@postgres:5432/simple_bank?sslmode=disable
    command:
      - /app/main
    entrypoint:
      - /app/wait-for.sh
      - postgres:5432
      - '--'
      - /app/start.sh
