apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data: 
  mapUsers: |
    - userarn: arn:aws:iam::545829658419:user/github-cli
      username: github-cli
      groups:
        - system:masters