name: Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
         version: 'latest' # default is latest stable
        id: install
        

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1
           mask-aws-account-id: 'false'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
      - name: Load secert and load in app.env file
        run: aws secretsmanager get-secret-value --secret-id simple-bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env
      
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: simplebank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t latest.
          docker push -a $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Deploy Image to Amazon EKS
        run: |
          kubectl apply -f eks/aws-auth.yml
          kubectl apply -f eks/deployment.yml
          kubectl apply -f eks/service.yml
          kubectl apply -f eks/issuer.yml
          kubectl apply -f eks/ingress.yml